# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Blog
paginate:       5
baseurl:        "/blog/"
url:            "https://dsinecos.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
sass:
  sass_dir: _sass
markdown:       kramdown

# About
author:
  name:         DS
  url:          "https://dsinecos.github.io"
  email:        dsinecos@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/dsinecos/dsinecos.github.io/

# Gems
plugins:
  - jekyll-paginate
