# Permalinks
#permalink:      /:year-:month-:day/:title
#permalink:      /:title
permalink:      /:categories/:title
# Setup
title:          Blog
paginate:       30
baseurl:        ""
url:            "https://dsinecos.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
sass:
  sass_dir: _sass
markdown:       kramdown
kramdown:
  input: GFM

# About
author:
  name:         divyanshu
  url:          "https://dsinecos.github.io"
  email:        dsinecos@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/dsinecos/dsinecos.github.io/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
